substitutions:
  _DESAFIO_HPA_GOLANG_VERSION: "1.0"
steps:
- id: "Build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/desafio_hpa_golang:latest', '-t', 'gcr.io/$PROJECT_ID/desafio_hpa_golang:${_DESAFIO_HPA_GOLANG_VERSION}', '.']

- id: "Rodando o teste"
  name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-t', '--name', 'desafio_hpa_golang', 'gcr.io/$PROJECT_ID/desafio_hpa_golang:latest', 'go', 'test']


images:
- 'gcr.io/$PROJECT_ID/desafio_hpa_golang:latest'
- 'gcr.io/$PROJECT_ID/desafio_hpa_golang:${_DESAFIO_HPA_GOLANG_VERSION}'
tags: ['cloud-builders-desafio-hpa-golang']