apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-hpa
spec:
    replicas: 3
    selector:
        matchLabels:
            app: go-hpa
    template:
        metadata:
            labels:
                app: go-hpa
        spec:
            containers:
            - name: go-hpa
              image: raphaellorencini/desafio_hpa_golang:latest
              ports:
              - containerPort: 8000
              resources:          
                requests:
                  memory: "64Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-hpa-service
spec:
  type: LoadBalancer
  selector:
    app: go-hpa
  ports:
  - port: 80
    targetPort: 8000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hpa
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 15